routes/web.php
<?php

use App\Http\Controllers\BuildingController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::resource('buildings', BuildingController::class);
Route::get('buildings/delete/{id}', [App\Http\Controllers\BuildingController::class, 'destroy'])->name('buildings.delete');

Route::get('/exportexcel', [App\Http\Controllers\BuildingController::class, 'export'])->name('exportexcel');

Route::get('/exportpdf', [App\Http\Controllers\BuildingController::class, 'exportpdf'])->name('exportpdf');

app/Models/Building.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Building extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable=['name','address','electricity'];

    public function images(){
        return $this->hasMany(BuildingMedia::class,'building_id');
    }
}

app/Http/Controllers/BuildingController.php
<?php

namespace App\Http\Controllers;

use App\Exports\BuildingExport;
use App\Exports\BuildingsExport;
use App\Models\Building;
use App\Models\BuildingMedia;
use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class BuildingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function export()
    {
        return Excel::download(new BuildingExport, 'buildings.xlsx');
    }

    public function exportpdf()
    {
        set_time_limit(6000);
        $buildings = Building::all();

        $view = view('exports.buildingpdf', [
            'buildings' => $buildings,
        ])->render();

        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($view);
        $dompdf->setPaper('A4', 'portrait'); // Set paper size and orientation
        $dompdf->render();

        return $dompdf->stream('data.pdf');
    }
    public function index()
    {
        $buildings = Building::orderBy('id','desc')->paginate(3);
        return view('buildings.index', get_defined_vars());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('buildings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'address' => 'required|string|max:255',
            'electricity' => 'required|numeric',
            'images' => 'required|array',
            'images.*' => 'image|mimes:jpeg,png,jpg,gif',
        ]);
        $building = Building::create($request->all());

        if ($request->hasFile('images')) {
            foreach ($request->file('images') as $image) {
                $name = time() . '_' . $image->getClientOriginalName();
                $image->move(public_path('storage/common_images'), $name);
                BuildingMedia::create([
                    'building_id' => $building->id,
                    'media_type' => 'image',
                    'media' => 'storage/' . 'common_images/' . $name
                ]);
            }
        }
        return redirect()->route('buildings.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function show(Building $building)
    {
        // dd($building->images[0]->media);
        return view('buildings.show', compact('building'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function edit(Building $building)
    {

        return view('buildings.edit', compact('building'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Building $building)
    {
        $building = Building::find($building->id);
        $building->update($request->all());
        return redirect()->route('buildings.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Building  $building
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $building = Building::find($id);
        if ($building) {
            $building->delete();
        }
        return redirect()->back();
    }
}

resources/views/buildings/create.blade.php
@extends('layouts.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Buildings</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Add Buildings</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Buildings</h3>
                        </div>
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                        <form method="post" action="{{route('buildings.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input name="name" type="text" class="form-control" id="exampleInputEmail1"
                                        placeholder="Enter text">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Electricity</label>
                                    <input type="number" name="electricity" class="form-control" id="exampleInputEmail1"
                                        placeholder="Enter text">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Address</label>
                                    <textarea class="form-control" name="address" id="" cols="30" rows="5"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputFile">Images</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" name="images[]" multiple class="custom-file-input" id="exampleInputFile">
                                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                        </div>

                                    </div>
                                </div>

                            </div>

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>



                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/buildings/edit.blade.php
@extends('layouts.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Add Buildings</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Add Buildings</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Add Buildings</h3>
                        </div>


                        <form method="post" action="{{route('buildings.update',$building->id)}}" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Name</label>
                                    <input name="name" type="text" class="form-control" id="exampleInputEmail1"
                                        placeholder="Enter text" value="{{$building->name}}">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Electricity</label>
                                    <input type="number" name="electricity" class="form-control" id="exampleInputEmail1"
                                        placeholder="Enter text" value="{{$building->electricity}}">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Address</label>
                                    <textarea class="form-control" name="address" id="" cols="30" rows="5">{{$building->address}}</textarea>
                                </div>


                            </div>

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>



                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/buildings/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Buildings</h3>
        </div>

        <div class="card-body">
            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">

                <div class="row">
                    <div class="col-sm-12">
                        <div class="text-right">
                            <a href="{{route('buildings.create')}}"><button class="btn btn-primary" type="button">Create</button></a>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <a href="/exportexcel"><button class="btn btn-primary" type="button">Export To Excel</button></a>
                        <a href="/exportpdf"><button class="btn btn-primary" type="button">Export To PDF</button></a>

                    </div>
                </div>
                <div class="row">

                    <div class="col-sm-12">
                        <table id="buildingstable" class="table table-bordered table-striped dataTable dtr-inline"
                            aria-describedby="example1_info">
                            <thead>
                                <tr>
                                    <th class="sorting sorting_asc" tabindex="0" aria-controls="example1" rowspan="1"
                                        colspan="1" aria-sort="ascending"
                                        aria-label="Rendering engine: activate to sort column descending">Image
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1"
                                        colspan="1" aria-label="Browser: activate to sort column ascending">Name</th>

                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1"
                                        colspan="1" aria-label="Engine version: activate to sort column ascending">Electricity</th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1"
                                        colspan="1" aria-label="CSS grade: activate to sort column ascending">Address
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach ($buildings as $item)

                                <tr class="odd">
                                    <td class="dtr-control sorting_1" tabindex="0">
                                        <img class="tableimage" src="{{$item->images->first() ? $item->images->first()->media : ''}}" alt="">
                                    </td>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->electricity}}</td>
                                    <td>{{$item->address}}</td>
                                    <td>
                                        <a href="{{route('buildings.show',$item->id)}}"><i class="fas fa-eye"></i></a>

                                        <a href="{{route('buildings.edit',$item->id)}}"><i class="fas fa-edit"></i></a>
                                        <a href="{{route('buildings.delete',$item->id)}}"><i class="fas fa-trash"></i></a>

                                    </td>
                                </tr>
                                @endforeach

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">Image</th>
                                    <th rowspan="1" colspan="1">Name</th>
                                    <th rowspan="1" colspan="1">Electricity</th>
                                    <th rowspan="1" colspan="1">Address</th>

                                </tr>
                            </tfoot>
                        </table>

                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-5">
                        <div class="dataTables_info" id="example1_info" role="status" aria-live="polite">Showing 1 to
                            {{$buildings->count()}} of {{$buildings->total()}} entries</div>
                    </div>
                    <div class="mt-4">

                        {{$buildings->links('pagination::bootstrap-4')}}
                    </div>

                </div>
            </div>
        </div>

    </div>
@push('page_scripts')
<script>
    $(document).ready(function() {
      $('#example').DataTable({
        dom: 'Bfrtip',
        buttons: [
          'excelHtml5',
          'pdfHtml5'
        ]
      });
    });
  </script>
@endpush
@endsection

resources/views/buildings/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-text-width"></i>
                Building {{$building->name}}
            </h3>
        </div>

        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-4">Building Name</dt>
                <dd class="col-sm-8">{{$building->name}}</dd>
                <dt class="col-sm-4">Electricity</dt>
                <dd class="col-sm-8">{{$building->electricity}}</dd>
                <dt class="col-sm-4">Address</dt>
                <dd class="col-sm-8">{{$building->address}}</dd>
                <dt class="col-sm-4">Images</dt>
                <dd class="col-sm-8">
                    @foreach ($building->images as $item)
                    <img class="tableimage" src="/{{$item->media}}" alt="">
                    @endforeach
                </dd>
            </dl>
        </div>

    </div>
@endsection